version: '3.7'
services:
  app:
    build: .
    command: sh -c 'bundle install && bundle exec rails s -b 0.0.0.0'
    user: "1000:1000"
    working_dir: /app
    ports:
      - 3050:3000
    volumes:
      - .:/app:cached
      - ruby_2_7_0_gems:/gems
    tty: true
    stdin_open: true
volumes:
  ruby_2_7_0_gems:
